server:
  port: 8080  # 스프링 서버 포트 지정

# MySQL DB 사용시
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
    url: jdbc:mysql://localhost:3306/testdb?autoReconnect=true # 접속 URL
    username: root # user
    password: password # password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # Hibernate 드라이버
    show-sql: true # 콘솔 쿼리 출력 여부
    properties:
      hibernate:
        format_sql: true # 쿼리 이쁘게 출력

# H2 In memory DB 사용시
#spring:
#  h2:
#    console:
#      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
#      path: /test_db  # 콘솔의 경로
#  datasource:
#    driver-class-name: org.h2.Driver  #h2 드라이버 설정
#    url: jdbc:h2:mem:testdb  #접속 URL
#    username: test  # 사용자 이름 (로그인 시 사용)
#    password: 1234  # 사용자 암호 (로그인 시 사용)
#    jpa:
#      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect # Hibernate 드라이버
#      show-sql: true # 콘솔 쿼리 출력 여부
#        properties:
#          hibernate:
#            format_sql: true # 쿼리 이쁘게 출력